### ISSUE TITLE
Sysstat_report error on run

### ISSUE THREAD

**Issue by sai-mike** [desbma/sysstat_mail_report#7]
I am running the latest version of the script on a Debian server with Python v3.10.5.  Here is the error I am getting:
 
mike@saivms:/var/log/sysstat$ sysstat_report.py daily saivms@xxx.com mike@xxx.com
Unable to get speed of interface eno2
Unable to get speed of interface eno3
Unable to get speed of interface eno4
2022-07-09 23:03:27,635 INFO Extracting CPU data...
2022-07-09 23:03:27,643 INFO Generating CPU TXT report...
2022-07-09 23:03:27,667 INFO Generating CPU PNG report...
2022-07-09 23:03:27,752 INFO Extracting MEM data...
2022-07-09 23:03:27,758 INFO Generating MEM TXT report...
2022-07-09 23:03:27,776 INFO Generating MEM PNG report...
2022-07-09 23:03:27,861 INFO Extracting NET data...
2022-07-09 23:03:27,880 INFO Generating NET TXT report...
Traceback (most recent call last):
  File "/usr/local/bin/sysstat_report.py", line 762, in <module>
    plotter.plot(
  File "/usr/local/bin/sysstat_report.py", line 654, in plot
    subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('gnuplot',)' returned non-zero exit status 1.

What do I need to do?

**Comment by sai-mike** [comment]
My error - I upgraded an old version of Python3 on the server.  I needed to install from source to get the latest version as only older versions are available from apt.  The source installs to a different path than apt on Debian so I needed to update my PYTHONPATH.
